tux3: Fix gcc-11 warnings for tests/link.c
tests/link.c: In function 'test_flink':
tests/link.c:113:9: error: '__flink_check_entries' accessing 8 bytes in a region of size 0 [-Werror=stringop-overflow=]
  113 |         __flink_check_entries(__h, __order, ARRAY_SIZE(__order));       \
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests/link.c:169:9: note: in expansion of macro 'flink_check_entries'
  169 |         flink_check_entries(&head);
      |         ^~~~~~~~~~~~~~~~~~~

gcc-11 warns about above, because maybe gcc doesn't know list is
always empty here. So this removes unnecessary check for empty list.

Signed-off-by: OGAWA Hirofumi <hirofumi@mail.parknet.co.jp>